name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Tells the runner to execute all following steps inside your specific folder
      - name: Set working directory
        run: echo "WORKING_DIR=YOUR_SUBFOLDER_NAME" >> $GITHUB_ENV # <-- CHANGE YOUR_SUBFOLDER_NAME HERE

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Change Gradle Wrapper Permissions
        run: chmod +x ./${{ env.WORKING_DIR }}/gradlew

      - name: Build Debug APK
        run: ./${{ env.WORKING_DIR }}/gradlew assembleDebug --project-dir ./${{ env.WORKING_DIR }}

      - name: Upload Compiled APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: ./${{ env.WORKING_DIR }}/app/build/outputs/apk/debug/app-debug.apk
